### ISSUE TITLE
Load validation aren't available in version 2.8.

### ISSUE THREAD

**Issue by Shashikant86** [natritmeyer/site_prism#147]
Just wondering why load validations are not appearing in version 2.8

Can't see class 'loadable.rb' in the downloaded Gem. Tried locking gem to 2.8 and downloding it from Github 

```
                 Undefined method `load_validation' for PageModels::RichTracks:Class (NoMethodError)
                   /Users/me/path/to/my/ruby/file.rb:52:in `<class:MyClass>'
                      /Users/me/path/to/my/ruby/file.rb:43:in `<module:PageModels>'
                   /Users/me/path/to/my/ruby/file.rb:1:in `<top (required)>'
                   /Users/me/gem/install/path/vendor/ruby/2.0.0/gems/require_all-1.3.3/lib/require_all.rb:108:in `require'
                 /Users/me/gem/install/path/vendor/ruby/2.0.0/gems/require_all-1.3.3/lib/require_all.rb:108:in `block in require_all'
                 /Users/me/gem/install/path/vendor/ruby/2.0.0/gems/require_all-1.3.3/lib/require_all.rb:106:in `each'
                  /Users/me/gem/install/path/vendor/ruby/2.0.0/gems/require_all-1.3.3/lib/require_all.rb:106:in `require_all'
                  /Users/me/gem/install/path/vendor/ruby/2.0.0/gems/require_all-1.3.3/lib/require_all.rb:153:in `block in require_rel'
                  /Users/me/gem/install/path/vendor/ruby/2.0.0/gems/require_all-1.3.3/lib/require_all.rb:152:in `each'
                /Users/me/gem/install/path/vendor/ruby/2.0.0/gems/require_all-1.3.3/lib/require_all.rb:152:in `require_rel'
               /Users/me/gem/install/path/features/support/env.rb:32:in `<top (required)>'
               /Users/me/gem/install/path/vendor/ruby/2.0.0/gems/cucumber-2.3.2/lib/cucumber/rb_support/rb_language.rb:96:in `load'
                 /Users/me/gem/install/path/vendor/ruby/2.0.0/gems/cucumber-2.3.2/lib/cucumber/rb_support/rb_language.rb:96:in `load_code_file'
                 /Users/me/gem/install/path/vendor/ruby/2.0.0/gems/cucumber-2.3.2/lib/cucumber/runtime/support_code.rb:142:in `load_file'
                  /Users/me/gem/install/path/vendor/ruby/2.0.0/gems/cucumber-2.3.2/lib/cucumber/runtime/support_code.rb:84:in `block in load_files!'
                   /Users/me/gem/install/path/vendor/ruby/2.0.0/gems/cucumber-2.3.2/lib/cucumber/runtime/support_code.rb:83:in `each'
                  /Users/me/gem/install/path/vendor/ruby/2.0.0/gems/cucumber-2.3.2/lib/cucumber/runtime/support_code.rb:83:in `load_files!'
                   /Users/me/gem/install/path/vendor/ruby/2.0.0/gems/cucumber-2.3.2/lib/cucumber/runtime.rb:254:in `load_step_definitions'
                  /Users/me/gem/install/path/vendor/ruby/2.0.0/gems/cucumber-2.3.2/lib/cucumber/runtime.rb:62:in `run!'
                 /Users/me/gem/install/path/vendor/ruby/2.0.0/gems/cucumber-2.3.2/lib/cucumber/cli/main.rb:32:in `execute!'
```

**Comment by natritmeyer** [comment]
Yeah, I need to release the latest version :)

**Comment by natritmeyer** [comment]
Oops. Meant to leave this open...

**Comment by mattpickle** [comment]
+1

**Comment by Neil-Aframe** [comment]
+1, just tried this after reading the docs, and it would be a nice feature to use in my tests

**Comment by luke-hill** [comment]
Re-open if issue persists. Similar issues being worked on
