### ISSUE TITLE
Unable to find a ReactModal as a section

### ISSUE THREAD

**Issue by khaidpham** [natritmeyer/site_prism#170]
SitePrism has been working great for my automation project until I needed to get a handle on a particular ReactModal object that works with straight capybara find command but not in SitePrism. I would really appreciate any help with this issue.

# calling find in pry debugger with would work
> find "div:nth-child(18) > div > div > div"
_=> #<Capybara::Node::Element tag="div" path="/html/body/div[6]/div/div/div">
"div:nth-child(18) > div > div > div"_
> find "div:nth-child(18) > div > div > div"
_=> #<Capybara::Node::Element tag="div" path="/html/body/div[6]/div/div/div">
[3] pry(#<RSpec::Core::ExampleGroup::Nested_1>)>_ 

# however calling SitePrism object @videos_page.clipping would not work.
> @videos_page.clipper
_ArgumentError: wrong number of arguments (given 2, expected 0)
from /Users/kpham/.rvm/gems/ruby-2.3.0@social/gems/site_prism-2.9/lib/site_prism/element_container.rb:28:in `initialize'_
> @videos_page.clipping
_ArgumentError: wrong number of arguments (given 2, expected 0)
from /Users/kpham/.rvm/gems/ruby-2.3.0@social/gems/site_prism-2.9/lib/site_prism/element_container.rb:28:in `initialize'_

```
class VideosPage <SitePrism::Page
  set_url "/videos"
  section :clipper, ClippingDialog, ".bc-dialog.bc-dialog-clipping"
  section :clipping, ClippingDialog, "div:nth-child(18) > div > div > div"
```

```
<body>
  <div class="ReactModalPortal">
    <div class="ReactModal__Overlay ReactModal__Overlay--after-open bc-modal bc-modal-clipping" data-reactid=".2">
     <div class="ReactModal__Content ReactModal__Content--after-open bc-modal-content bc-modal-content-clipping" tabindex="-1" data-reactid=".2.0">
       **<div role="dialog" class="bc-dialog bc-dialog-clipping" data-reactid=".2.0.0">**
```

**Comment by khaidpham** [comment]
Found the issue in section definition, cut and paste error.

`class ClippingDialog <SitePrism::Page `

should be:

`class ClippingDialog <SitePrism::Section`

This issue is resolved.
