### ISSUE TITLE
Unable to activate site_prism-2.13, because capybara-3.2.1 conflicts with capybara (~> 2.12) (Gem::ConflictError)

### ISSUE THREAD

**Issue by vanessamilagres** [natritmeyer/site_prism#272]
## Environment
- Mac
- Gems: 
       gem 'cucumber' , (3.1.1)
       gem 'rspec' (3.7.0)
       gem 'capybara' (2.18.0)
       gem 'selenium-webdriver' (3.12.0)
       gem 'site_prism' (2.13)
- Cucumber Tests
- Firefox

## Expected Behavior
Run my tests

## Actual Behavior
```
Unable to activate site_prism-2.13, because capybara-3.2.1 conflicts with capybara (~> 2.12) (Gem::ConflictError)
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/rubygems/specification.rb:2325:in `raise_if_conflicts'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/rubygems/specification.rb:1438:in `activate'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/rubygems.rb:224:in `rescue in try_activate'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/rubygems.rb:217:in `try_activate'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
/Users/vanessamilagres/Documents/ninjamotors/features/support/env.rb:3:in `<top (required)>'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-3.1.1/lib/cucumber/glue/registry_and_more.rb:107:in `load'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-3.1.1/lib/cucumber/glue/registry_and_more.rb:107:in `load_code_file'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-3.1.1/lib/cucumber/runtime/support_code.rb:144:in `load_file'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-3.1.1/lib/cucumber/runtime/support_code.rb:85:in `block in load_files!'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-3.1.1/lib/cucumber/runtime/support_code.rb:84:in `each'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-3.1.1/lib/cucumber/runtime/support_code.rb:84:in `load_files!'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-3.1.1/lib/cucumber/runtime.rb:272:in `load_step_definitions'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-3.1.1/lib/cucumber/runtime.rb:68:in `run!'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-3.1.1/lib/cucumber/cli/main.rb:34:in `execute!'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-3.1.1/bin/cucumber:9:in `<top (required)>'
/usr/local/bin/cucumber:23:in `load'
/usr/local/bin/cucumber:23:in `<main>'
```
## Steps to reproduce
- enter the project
- run cucumber -t @doing

**Comment by luke-hill** [comment]
This is a simple error message dictating that you have a conflict in your Gemfile.

Re-force your gemfile to use Capybara version 2.x and then you will have no issues.

For future reference. The work to enable Capybara 3 functionality will be released provisionally with site_prism 2.14

**Comment by vanessamilagres** [comment]
I forced the installation of my gems to one that should work, but still giving that same message.

**Comment by luke-hill** [comment]
If something weird is happening around this, we cannot do anything.

You could forcibly uninstall capybara 3.2 by doing `gem uninstall capybara` and then doing all versions. Then doing a rebundle. Ensuring you lock your gemfile to 2.x
